### ISSUE TITLE
Docs on: Required CSS or load fails

### ISSUE THREAD

**Issue by lossendae** [xkjyeah/vue-google-maps#479]
Hello, i like your component however i think you should not note somewhere in the README or in the wiki that the CSS is required.

I've just spent 4 hours wondering why the script was working on dev and not in build production.

My config is in a legacy application with multiple entry point and not state of the art webpack config either. But there was no error whatsoever.

My error was exactly like the following issue : https://github.com/xkjyeah/vue-google-maps/issues/419

It turns out that I had to include the CSS of component located in `src/components/map.vue`: 
```css
.vue-map-container {
  position: relative;
}

.vue-map-container .vue-map {
  left: 0; right: 0; top: 0; bottom: 0;
  position: absolute;
}
.vue-map-hidden {
  display: none;
}
```
Otherwise the iframe stay collapsed and nothing tells you what's going wrong with your code which works on dev.
