### ISSUE TITLE
Is it possible to make it responsive?

### ISSUE THREAD

**Issue by hifall** [xkjyeah/vue-google-maps#642]
I've found that when viewed in mobile Safari, part of the map is hidden.

Is it possible to make the plugin responsive?

Thanks!

**Comment by webistomin** [comment]
> I've found that when viewed in mobile Safari, part of the map is hidden.
> 
> Is it possible to make the plugin responsive?
> 
> Thanks!

```css
.map-responsive {
    overflow:hidden;
    padding-bottom:56.25%;
    position:relative;
    height:0;
}
.map-responsive iframe{
    left:0;
    top:0;
    height:100%;
    width:100%;
    position:absolute;
}
```
